### PR TITLE
Add unmaintained notice

### PR DESCRIPTION
**Pull request by ericglau**
Adds unmaintained notice to app and readme. Screenshot:

---

Screen Shot 2022-08-10 at 1 59 53 PM

### CODE REVIEW

**Comment by ericglau** [comment]
@martriay Can you please review?

**Review by martriay — APPROVED** [review]
Looks good! This needs to be deployed to IPFS and the new hash/link has to be shared with the Gnosis team.

**Comment by ericglau** [comment]
@martriay can you merge this PR? I don't have write access

**Comment by martriay** [comment]
@ericglau done. Also granted write access to @OpenZeppelin/development.

**Comment by martriay** [comment]
@ericglau done. Also granted write access to @OpenZeppelin/development. cc/ @spalladino.

**Pull request merged**
